-- Execute all SQL statements, in sequential order, from the top of this file
-- to create the tables or to "reset" the database to the expected structure


-- TODO: add your tables structure

DROP TABLE IF EXISTS recipes;


CREATE TABLE recipes
(
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    title         VARCHAR(255),
    contributor   VARCHAR(255),
    category      VARCHAR(255),
    instructions  VARCHAR
);

INSERT INTO recipes (title, contributor, category, instructions)
VALUES ("Sausage, Egg, and Cheese Biscuit Casserole","Kathryn Hendrix","breakfast","1 (16.3 ounce) can refrigerated biscuits (such as Pillsbury Grands! Original), 1 pound bulk pork sausage,1 1/2 cups shredded Cheddar cheese, 8 large eggs, 1 cup milk, 1/2 teaspoon salt, 1/2 teaspoon ground black pepper Gather all ingredients. Preheat the oven to 425 degrees F (220 degrees C). Grease a 9x13-inch baking dish. Line prepared baking dish with the biscuits, pressing to form an even layer. Bake in the preheated oven until puffed and lightly browned, about 8 minutes. Reduce oven temperature to 375 degrees F (190 degrees C). (Leave the oven door open for a bit to let the oven cool down.) Meanwhile, heat a large skillet over medium-high heat. Add sausage to skillet; cook and stir until fully cooked and browned, about 10 minutes; drain fat. Sprinkle cooked sausage and cheese evenly over baked biscuits Whisk together eggs, milk, salt, and pepper in a large bowl. Pour egg mixture over sausage and cheese. (The egg mixture won’t cover the cheese and sausage at this point, but will expand as it bakes.) Bake until casserole is set and internal temperature registers 165 degrees F (74 degrees C), about 25 minutes. Enjoy")

INSERT INTO recipes (title, contributor, category, instructions)
VALUES ("Ultimate Potato Soup","allrecipes.com","soup","This potato soup comes together quickly with basic ingredients. You''ll find the full recipe below, but here''s a brief overview of what you can expect. Cook the Bacon Cook bacon in a Dutch oven over medium-high heat until brown and crispy. Drain bacon on paper towels and drain most (but not all!) of the bacon grease. Cook the Soup Cook the celery, onion, and garlic in the remaining bacon grease. Add cubed potatoes and toss with veggies. Return the bacon to the pan and cover all the ingredients with chicken stock. Cover and simmer until the potatoes are tender. In a separate skillet, whisk butter into melted flour until slightly thickened. Whisk in heavy cream, tarragon, and cilantro. Bring the mixture to a boil and cook until thick and creamy. Stir cream mixture into potato mixture. Blend and Serve Transfer half of the soup to a blender and puree, then return to the Dutch oven. Season to taste and serve with your favorite toppings, such as crumbled bacon or shredded Cheddar cheese. Best Potatoes for Potato Soup Russet potatoes work well for this soup because they are starchy and fall apart easily during cooking, resulting in a smooth texture. Stay away from waxy potatoes as they won''t break down as well. How to Thicken Potato Soup We love this top-rated recipe because it results in a thick, satisfying soup. If you somehow end up with a thinner consistency than you''d like, though, there are a few ways to thicken it. For an easy fix, just add more boiled potatoes and incorporate them into the soup or stir in instant potato flakes. You can also make a slurry with one part water and one part cornstarch. Stir the slurry slowly into the soup until you''ve reached the desired thickness.")

INSERT INTO recipes (title, contributor, category, instructions)
VALUES ("Rotisserie chicken bake","The daily gourmet","dinner","6 ounces high protein pasta, 4 ounces chopped broccoli florets, 8 ounces rotisserie chicken, cut into bite-sized pieces, 2-ounce chunk Parmesan cheese, 8ounces high protein cottage cheese, 4 fluid ounces high protein milk, 2 ounces low-fat cream cheese, ½ teaspoon granulated garlic,½ teaspoon Cantanzaro herbs, 4 ounces shredded mozzarella cheese. Directions Preheat the oven to 375 degrees F (190 degrees C). Lightly grease a casserole dish. Bring a large pot of salted water to a boil, and cook pasta for 7 minutes. Add broccoli; cook for 2 minutes more. Drain pasta and broccoli. Add Parmesan chunk to a high powered blender, such as a Vitamix. Blend on High until Parmesan chunk is finely ground. Add in cottage cheese, milk, and cream cheese; blend until smooth. Pour mixture into a large bowl. Stir in granulated garlic and Cantanzaro herbs. Add in the pasta, broccoli, chicken, and half the mozzarella cheese; stir until combined. Pour into the prepared casserole dish. Top with remaining mozzarella cheese. Pour into the prepared casserole dish. Top with remaining mozzarella cheese. Bake in the preheated oven until bubbly, about 30 minutes. Serve immediately.")

INSERT INTO recipes (title, contributor, category, instructions)
VALUES ("Smashed Chicken Parmesian Texas Toast", "Nicole McLaughin","lunch","Ingredients:1 pound ground chicken, 1 teaspoon kosher salt, ½ teaspoon freshly ground black pepper, 1teaspoon garlic powder, ¼ teaspoon Italian seasoning, ¼ teaspoon crushed red pepper, ¼ cup freshly grated Parmesan cheese, 1 package frozen garlic flavored Texas toast, 4 teaspoons olive oil, ½ cup marinara sauce, 1 cup shredded mozzarella cheese. Directions Combine ground chicken, salt, pepper, garlic powder, Italian seasoning, and grated Parmesan in a bowl. Spread mixture in a thin layer over one side of each toast, being sure to reach the edges of the bread. Heat a large nonstick skillet over medium-high heat. Add 2 teaspoons oil and place half of the toasts, chicken side down, in the hot skillet, lightly pressing down on each one with a spatula. Cook, undisturbed, until golden brown and cooked through, about 4 minutes. Flip, turn heat to low, and top each toast with 1 tablespoon marinara sauce and 2 tablespoons mozzarella cheese. Cover the skillet and turn off the heat, and let stand until the cheese is completely melted, about 2 minutes. Repeat with remaining toasts.")

INSERT INTO recipes (title, contributor, category, instructions)
VALUES ("Cherry cheesecake dump cake", "Nicole McLaughin","dessert","Ingredients:1 can cherry pie filling, 8 ounces cream cheese, softened 1 large egg, ½ cup white sugar, 1 teaspoon vanilla extract, 1 (15.25 ounce) box vanilla cake mix, 10 tablespoons butter, melted. Directions Preheat the oven to 350 degrees F (180 degrees C). Pour pie filling into a 9x13-inch baking dish. Beat cream cheese, egg, sugar and vanilla together in a bowl with an electric mixer until well combined and smooth. Spoon mixture over pie filling. Spread cake mix in an even layer over cream cheese mixture, taking care not to mix the layers. Pour melted butter over evenly over the top. Bake in the preheated oven until golden brown and bubbly, 40 to 50 minutes. Let stand 10 minutes before serving.")
