-- Execute all SQL INSERT statements, in sequential order, from the top of this file
-- to populate the tables with sample data


-- Inserting data with the updated column order (category before contributor)
INSERT INTO recipes (title, category, contributor, ingredients, instructions)
VALUES
    ('Spaghetti Bolognese', 'Main Course', 'Alice', 'spaghetti, ground beef, tomato sauce, onions, garlic', 'Boil spaghetti, cook beef with onions and garlic, mix with sauce, serve with spaghetti.'),
    ('Blueberry Pancakes', 'Breakfast', 'Bob', 'flour, sugar, milk, eggs, blueberries', 'Mix dry ingredients, add milk and eggs, fold in blueberries, cook on griddle.'),
    ('Chicken Curry', 'Main Course', 'Carlos', 'chicken, coconut milk, curry powder, onions, garlic', 'Brown chicken, sauté onions and garlic, add curry powder and coconut milk, simmer until cooked.'),
    ('Vegetable Stir Fry', 'Main Course', 'Dana', 'broccoli, carrots, bell peppers, soy sauce, garlic', 'Stir fry vegetables in hot oil, add soy sauce and garlic, cook until tender.'),
    ('Chocolate Chip Cookies', 'Dessert', 'Evelyn', 'flour, sugar, butter, chocolate chips, eggs', 'Mix ingredients, spoon onto baking sheet, bake at 350°F for 10 minutes.'),
    ('Sausage, Egg, and Cheese Biscuit Casserole', 'Breakfast', 'Kathryn Hendrix', '1 (16.3 ounce) can refrigerated biscuits (such as Pillsbury Grands! Original), 1 pound bulk pork sausage, 1 1/2 cups shredded Cheddar cheese, 8 large eggs, 1 cup milk, 1/2 teaspoon salt, 1/2 teaspoon ground black pepper', 'Preheat the oven to 425 degrees F (220 degrees C). Grease a 9x13-inch baking dish. Line prepared baking dish with the biscuits, pressing to form an even layer. Bake in the preheated oven until puffed and lightly browned, about 8 minutes. Reduce oven temperature to 375 degrees F (190 degrees C). (Leave the oven door open for a bit to let the oven cool down.) Meanwhile, heat a large skillet over medium-high heat. Add sausage to skillet; cook and stir until fully cooked and browned, about 10 minutes; drain fat. Sprinkle cooked sausage and cheese evenly over baked biscuits. Whisk together eggs, milk, salt, and pepper in a large bowl. Pour egg mixture over sausage and cheese. (The egg mixture won’t cover the cheese and sausage at this point, but will expand as it bakes.) Bake until casserole is set and internal temperature registers 165 degrees F (74 degrees C), about 25 minutes. Enjoy'),
    ('Ultimate Potato Soup', 'Soup', 'allrecipes.com', 'bacon, celery, onion, garlic, potatoes, chicken stock, butter, heavy cream, tarragon, cilantro', 'Cook bacon in a Dutch oven until crispy. Drain bacon and cook vegetables in the remaining grease. Add potatoes, return bacon, cover with stock, and simmer. In a separate skillet, cook butter and flour, add heavy cream and herbs. Combine both mixtures and blend half of the soup. Serve with toppings like crumbled bacon or shredded cheddar cheese.'),
    ('Rotisserie Chicken Bake', 'Main Course', 'The Daily Gourmet', 'high protein pasta, broccoli, rotisserie chicken, Parmesan cheese, cottage cheese, milk, cream cheese, garlic, herbs, mozzarella cheese', 'Preheat the oven to 375°F. Cook pasta and broccoli. Blend Parmesan with cottage cheese, milk, and cream cheese. Combine with pasta, chicken, and cheese, bake for 30 minutes until bubbly.'),
    ('Smashed Chicken Parmesan Texas Toast', 'Main Course', 'Nicole McLaughlin', 'ground chicken, salt, pepper, garlic powder, Italian seasoning, red pepper, Parmesan cheese, frozen garlic Texas toast, olive oil, marinara sauce, mozzarella cheese', 'Combine ground chicken and seasonings, spread on Texas toast, cook in skillet, top with marinara and mozzarella. Bake until golden and melted.'),
    ('Cherry Cheesecake Dump Cake', 'Dessert', 'Nicole McLaughlin', 'cherry pie filling, cream cheese, egg, white sugar, vanilla cake mix, butter', 'Preheat the oven to 350°F. Layer pie filling, cream cheese mixture, and cake mix in a dish, pour butter over top, and bake until golden and bubbly. Let cool before serving.')
;

-- Five new recipes to add to database
INSERT INTO recipes (title, category, contributor, ingredients, instructions)
VALUES
    ('Authentic Spaghetti Carbonara', 'Main Course', 'Food Network', 'spaghetti, pancetta, eggs, Parmesan cheese, black pepper, salt, parsley', 'Bring a large pot of salted water to a boil and cook spaghetti until al dente. Meanwhile, cook pancetta in a skillet until crisp. In a bowl, whisk eggs, cheese, and pepper. Drain pasta, reserving some water. Add hot pasta to pancetta, remove from heat, then quickly stir in egg mixture until it thickens but doesn''t scramble. Thin with pasta water if needed. Season with salt and garnish with parsley.'),

    ('Chicken Tikka Masala', 'Main Course', 'Allrecipes', 'boneless chicken, yogurt, lemon juice, cumin, cinnamon, cayenne, ginger, garlic, tomato sauce, heavy cream, cilantro, garam masala', 'Marinate chicken in yogurt, lemon juice, and spices for at least 1 hour. Grill or pan-cook chicken until nearly done. In a large pan, sauté onions, add more spices, then add tomato sauce. Add grilled chicken and simmer. Finish with heavy cream and cilantro. Serve hot with rice or naan bread.'),

    ('Classic Apple Crumble', 'Dessert', 'Taste of Home', 'apples, sugar, cinnamon, nutmeg, lemon juice, flour, brown sugar, butter, oats, salt', 'Preheat oven to 375°F. Toss sliced apples with sugar, cinnamon, nutmeg, and lemon juice in a baking dish. For topping, combine flour, brown sugar, butter, oats, and salt until crumbly. Sprinkle topping over apples and bake for 35-40 minutes until golden and bubbly. Serve warm with ice cream.'),

    ('Gingerbread Cookies', 'Dessert', 'Sally''s Baking Addiction', 'flour, baking soda, ginger, cinnamon, cloves, nutmeg, salt, butter, brown sugar, molasses, egg, vanilla', 'In a bowl, whisk flour, baking soda, and spices. In another bowl, beat butter and brown sugar until fluffy, then add molasses, egg, and vanilla. Gradually mix in dry ingredients. Chill dough for at least 3 hours. Roll dough to 1/4-inch thickness, cut shapes, and bake at 350°F for 8-10 minutes. Cool completely before decorating.'),

    ('Easy Vegetable Stir Fry', 'Main Course', 'Gimme Some Oven', 'broccoli, carrots, bell peppers, snow peas, mushrooms, garlic, ginger, soy sauce, sesame oil, cornstarch, brown sugar, rice vinegar, sriracha', 'Prepare sauce by mixing soy sauce, sesame oil, cornstarch, brown sugar, rice vinegar, and sriracha. Heat oil in a wok or large skillet over high heat. Add vegetables in order of cooking time (harder vegetables first). Add minced garlic and ginger. Pour sauce over vegetables and cook until thickened. Serve hot over rice or noodles.')
;
